<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.pkWpgsg' shared service.

return $this->privates['.service_locator.pkWpgsg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\SecuriteController::liste' => ['privates', '.service_locator.jBD0lq.', 'get_ServiceLocator_JBD0lq_Service.php', true],
    'App\\Controller\\SecuriteController::register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\SecuriteController::update' => ['privates', '.service_locator.wLSO0UM', 'get_ServiceLocator_WLSO0UMService.php', true],
    'App\\Controller\\SecuriteController:liste' => ['privates', '.service_locator.jBD0lq.', 'get_ServiceLocator_JBD0lq_Service.php', true],
    'App\\Controller\\SecuriteController:register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\SecuriteController:update' => ['privates', '.service_locator.wLSO0UM', 'get_ServiceLocator_WLSO0UMService.php', true],
], [
    'App\\Controller\\SecuriteController::liste' => '?',
    'App\\Controller\\SecuriteController::register' => '?',
    'App\\Controller\\SecuriteController::update' => '?',
    'App\\Controller\\SecuriteController:liste' => '?',
    'App\\Controller\\SecuriteController:register' => '?',
    'App\\Controller\\SecuriteController:update' => '?',
]);
