<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Fjp7tCr' shared service.

return $this->privates['.service_locator.Fjp7tCr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ApiController::ajout' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\SecuriteController::ajout' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\SecuriteController::register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\SecuriteController::update' => ['privates', '.service_locator.fDbIXxi', 'get_ServiceLocator_FDbIXxiService.php', true],
    'App\\Controller\\ApiController:ajout' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\SecuriteController:ajout' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\SecuriteController:register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\SecuriteController:update' => ['privates', '.service_locator.fDbIXxi', 'get_ServiceLocator_FDbIXxiService.php', true],
], [
    'App\\Controller\\ApiController::ajout' => '?',
    'App\\Controller\\SecuriteController::ajout' => '?',
    'App\\Controller\\SecuriteController::register' => '?',
    'App\\Controller\\SecuriteController::update' => '?',
    'App\\Controller\\ApiController:ajout' => '?',
    'App\\Controller\\SecuriteController:ajout' => '?',
    'App\\Controller\\SecuriteController:register' => '?',
    'App\\Controller\\SecuriteController:update' => '?',
]);
