<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBVxNxcD\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBVxNxcD/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBVxNxcD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBVxNxcD\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBVxNxcD\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BVxNxcD',
    'container.build_id' => '0639a5fb',
    'container.build_time' => 1564244905,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBVxNxcD');
