<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXIiWTGY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXIiWTGY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXIiWTGY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXIiWTGY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXIiWTGY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XIiWTGY',
    'container.build_id' => '06148495',
    'container.build_time' => 1564168013,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXIiWTGY');
