<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerYqY1X42\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYqY1X42/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYqY1X42.legacy');
=======
if (\class_exists(\ContainerXIiWTGY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXIiWTGY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXIiWTGY.legacy');
>>>>>>> d03c8b806dd2f50939d11701c1a34fa7009bcb6f

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerYqY1X42\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYqY1X42\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YqY1X42',
    'container.build_id' => 'ced5dd6a',
    'container.build_time' => 1564240146,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYqY1X42');
=======
    \class_alias(\ContainerXIiWTGY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXIiWTGY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XIiWTGY',
    'container.build_id' => '06148495',
    'container.build_time' => 1564168013,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXIiWTGY');
>>>>>>> d03c8b806dd2f50939d11701c1a34fa7009bcb6f
